language: groovy
services:
  - mongodb
  - redis-server
branches:
  only:
    - master
script: ./grailsw refresh-dependencies
  && ./grailsw clean
  && ./grailsw "test-app -coverage -xml"
after_success: ./grailsw coveralls
